asymmetric_title = "About Asymmetric Encryption section"
asymmetric_text = ("The <b>Asymmetric Encryption</b> section, offers tools for implementing and exploring public-key cryptography algorithms,<br>"
                "which are essential for secure communication, digital signatures, and data integrity. "
                "This section provides both traditional and modern cryptographic techniques, "
                "empowering users to experiment with key generation, encryption, decryption, and signature verification."
                "<p><strong>Public-Key Algorithms:</strong></p>"
                "<ul>"
                "<li><strong>RSA: </strong>Implement RSA encryption and decryption, including analyzing vulnerabilities like the RSA Wiener Attack. </li>"
                "<li><strong>ElGamal: </strong>Perform secure encryption using the ElGamal cryptosystem. </li>"
                "<li><strong>Diffie-Hellman Key Exchange: </strong>Generate shared secrets securely for symmetric encryption. </li>"
                "</ul>"
                "<p><strong>Advanced Algorithms:</strong></p>"
                "<ul>"
                "<li><b>Cramer-Shoup Encryption and Decryption:</b> A robust cryptosystem resistant to adaptive chosen-ciphertext attacks.</li>"
                "<li><b>Paillier Encryption and Decryption:</b> Enable homomorphic encryption for secure computations on encrypted data.</li>"
                "<li><b>Kyber KEM:</b>Implement post-quantum cryptography with the Kyber Key Encapsulation Mechanism.</li>"
                "</ul>"
                "<p><strong>Digital Signatures and Certificates:</strong></p>"
                "<ul>"
                "<li><b>Digital Signature Algorithm (DSA) and ECDSA: </b>Verify message authenticity using secure digital signatures. </li>"
                "<li><b>EdDSA:</b>Implement modern elliptic curve-based signature schemes.</li>"
                "<li><b>Certificate Signing Requests (CSR): </b>Create CSRs for obtaining SSL/TLS certificates.</li>"
                "</ul>"
                "<p><strong>Elliptic Curve Cryptography (ECC):</strong></p>"
                "<ul>"
                "<li><b>ECDH: </b>Perform Elliptic Curve Diffie-Hellman for secure key exchanges. </li>"
                "</ul>")

symmetric_title = "About Symmetric Encryption Section"
symmetric_text = ("The <b>Symmetric Encryption</b> Section provides users with tools to perform encryption and decryption using "
                "a range of symmetric algorithms. These algorithms are ideal for securing data "
                "with a single shared key, offering both speed and strength for various <br>use cases. "
                "<p><strong>AES and DES:</strong></p>"
                "<ul>"
                "<li><strong>AES Encryption and Decryption: </strong>Implement the Advanced Encryption Standard (AES), a highly secure and widely adopted symmetric algorithm. </li>"
                "<li><strong>DES Encryption and Decryption: </strong>Use the Data Encryption Standard (DES), with options to experiment with this historic but less secure algorithm. </li>"
                "</ul>"
                "<p><strong>Other Algorithms:</strong></p>"
                "<ul>"
                "<li><b>3DES Encryption and Decryption: </b>Apply Triple DES for enhanced security over standard DES.</li>"
                "<li><b>FERNET Encryption: </b>Secure data with the modern and easy-to-use Fernet encryption scheme.</li>"
                "</ul>"
                "<p><strong>Legacy Algorithms:</strong></p>"
                "<ul>"
                "<li><b>RC2 and RC5 Encryption/Decryption: </b>Explore these historic cryptographic algorithms for legacy compatibility.</li>"
                "<li><b>Blowfish: </b>A fast and effective block cipher suitable for secure encryption needs.</li>"
                "</ul>"
                "<p><strong>Lightweight Ciphers:</strong></p>"
                "<ul>"
                "<li><b>Camellia: </b>Utilize this high-performance encryption algorithm, designed for strong security and speed.</li>"
                "<li><b>Twofish: </b>Experiment with a flexible and fast successor to Blowfish.</li>"
                "<li><b>Serpent: </b>Work with this highly secure encryption method, designed as a candidate for AES.</li>"
                "</ul>")

ciphers_title = "About Ciphers Section"
ciphers_text = ("The <b>Ciphers</b> Section allows users to delve into the fascinating world of cryptography, "
                "exploring both historical and contemporary encryption techniques. This section is perfect for "
                "cryptography enthusiasts, learners, and professionals seeking to understand the evolution of encryption methods."
                "<p><strong>Classical Ciphers:</strong></p>"
                "<ul>"
                "<li><strong>Caesar Cipher: </strong>Experiment with one of the earliest known substitution ciphers. </li>"
                "<li><strong>Bacon Cipher: </strong>Encode messages using this 16th-century cipher based on binary encoding. </li>"
                "<li><strong>Affine Cipher: </strong>Perform encryption and decryption using affine transformations. </li>"
                "</ul>"
                "<p><strong>Modern Ciphers:</strong></p>"
                "<ul>"
                "<li><b>ChaCha20 and ChaCha20-Poly1305: </b>Utilize modern, secure stream ciphers for encryption. </li>"
                "<li><b>Rabbit Stream Cipher: </b>Perform fast and secure stream encryption. </li>"
                "<li><b>RC4: </b>Work with the once-popular RC4 stream cipher. </li>"
                "</ul>"
                "<p><strong>Historical Machines:</strong></p>"
                "<ul>"
                "<li><b>Enigma Machine: </b> Simulate the famous WWII encryption machine and its workings.</li>"
                "</ul>"
                "<p><strong>Other Ciphers:</strong></p>"
                "<ul>"
                "<li><b>Vigenère Cipher: </b>Experiment with this polyalphabetic cipher. </li>"
                "<li><b>SM4: </b>Work with this block cipher widely used in Chinese cryptographic standards. </li>"
                "<li><b>TEA, XTEA and XXTEA: </b>Explore lightweight and fast encryption algorithms..</li>"
                "</ul>")

hashalgo_title = "About Hashing Algorithms section"
hashalgo_text = ("The <b>Hashing Algorithms</b> section is dedicated to cryptographic hashing functions, essential for "
                "ensuring data integrity, secure password storage, and digital signatures. This section covers a variety of"
                "popular and secure hashing algorithms, offering tools for creating, analyzing and identifying hash values."
                "<p><strong>Popular hashing algorithms:</strong></p>"
                "<ul>"
                "<li><strong>MD4 and MD5: </strong>Explore these older yet historically significant hashing algorithms. </li>"
                "<li><strong>SHA-1: </strong>Analyze this once-dominant but now deprecated hash function due to vulnerabilities. </li>"
                "<li><strong>SHA-256, SHA-384, SHA-512: </strong>Experiment with these secure and widely-used hash functions in the SHA-2 family. </li>"
                "</ul>"
                "<p><strong>Modern and secure hash functions:</strong></p>"
                "<ul>"
                "<li><b>BLAKE2 and BLAKE3: </b>Use these high-performance, modern cryptographic hash functions, designed as faster and secure alternatives to SHA-3. </li>"
                "<li><b>Whirlpool: </b>Implement this less-common but robust hashing algorithm. </li>"
                "<li><b>RC4: </b>Work with the once-popular RC4 stream cipher. </li>"
                "</ul>"
                "<p><strong>Password Hashing:</strong></p>"
                "<ul>"
                "<li><b>Bcrypt: </b>Securely hash and verify passwords using this widely adopted password hashing algorithm.</li>"
                "</ul>"
                "<p><strong>Other:</strong></p>"
                "<ul>"
                "<li><b>Hash Identifier: </b>Identify the type of a given hash value based on its structure and characteristics. </li>"
                "</ul>")

encoders_title = "About Encoders section"
encoders_text = ("The <b>Encoders</b> section allows users to encode and decode data using a wide range of "
                "encoding techniques, from simple text transformations to complex encoding schemes used in modern systems. "
                "<p><strong>Standard Encoding Schemes:</strong></p>"
                "<ul>"
                "<li><strong>BASE32, BASE45, BASE58, BASE62, BASE64, BASE85, and BASE92: </strong>Encode and decode data using popular BASE encodings for data representation and storage. </li>"
                "</ul>"
                "<p><strong>Character-Based Transformations:</strong></p>"
                "<ul>"
                "<li><b>A1Z26 Encode/Decode: </b>Convert text into numbers based on letter positions in the alphabet. </li>"
                "<li><b>Braille: </b>Translate text into Braille representation for accessibility purposes. </li>"
                "<li><b>Morse Code:</b> Encode and decode messages using the classic Morse code for communication.</li>"
                "</ul>"
                "<p><strong>Web and Network Encodings:</strong></p>"
                "<ul>"
                "<li><b>URL Encode/Decode: </b>Transform text to be safely included in URLs or restore encoded URLs to their original form.</li>"
                "</ul>"
                "<p><strong>Text-to-Special Formats:</strong></p>"
                "<ul>"
                "<li><b>Charcode: </b>Convert text into its corresponding character codes or reverse the process. </li>"
                "<li><b>Quoted Printable: </b>Encode or decode text into quoted-printable format, commonly used in email systems.</li>"
                "</ul>")

converters_title = "About Converters section"
converters_text = ("The <b>Converters</b> section simplifies data transformations by providing utilities to seamlessly "
                "convert between numerical systems, character formats, timestamps, and other specialized representations. "
                "<p><strong>Text and Binary Conversions:</strong></p>"
                "<ul>"
                "<li><b>Octal converter: </b>Convert to octal representation and back. </li>"
                "<li><b>Binary converter: </b>Transform text into binary format or decode binary back to readable text. </li>"
                "<li><b>ASCII converter: </b>Encode text to ASCII values and vice versa.</li>"
                "</ul>"
                "<p><strong>Numerical System Conversions:</strong></p>"
                "<ul>"
                "<li><b>Hex converter: </b>Perform hexadecimal conversions for text representation.</li>"
                "<li><b>Radix converter: </b>Convert numbers to different bases (e.g., base-2, base-16).</li>"
                "</ul>"
                "<p><strong>Cryptographic Format Conversions:</strong></p>"
                "<ul>"
                "<li><b>DER to PEM / PEM to DER: </b>Convert cryptographic key formats between PEM (Base64 encoded) and DER (binary encoded). </li>"
                "</ul>"
                "</ul>"
                "<p><strong>Codepoint and Character Conversions:</strong></p>"
                "<ul>"
                "<li><b>Codepoint Converter: </b>Convert text to Unicode code points and back.</li>"
                "<li><b>HTML Entity Converter: </b>Transform text into HTML entities for web compatibility.</li>"
                "</ul>")

file_handling_title = "About File handling Section"
file_handling_text = ("The <b>File Handling</b> section, provides a wide range of utilities for<br>"
                "secure file operations and data transformation. This section allows users to seamlessly handle "
                "encryption, decryption, file conversions and other specialized tasks, such as:"
                "<p><strong>Encryption and Decryption Utilities:</strong></p>"
                "<ul>"
                "<li><strong>Fernet file encryption and decryption: </strong>Securely encrypt and decrypt files using the robust Fernet encryption method. </li>"
                "</ul>"
                "<p><strong>File Conversion Tools:</strong></p>"
                "<ul>"
                "<li>Convert <b>CSV</b> to <b>JSON</b> or <b>JSON</b> to <b>CSV</b> for easier data processing.</li>"
                "<li>Transform images to PDF <b>(IMG2PDF)</b> and vice versa <b>(PDF2IMG)</b>.</li>"
                "<li>Extract EXIF metadata from images for analysis.</li>"
                "</ul>"
                "<p><strong>Password-Protected Operations:</strong></p>"
                "<ul>"
                "<li>Open and manage <b>ZIP files with passwords</b> and securely access folders with similar protection. </li>"
                "</ul>"
                "<p><strong>File Analysis:</strong></p>"
                "<ul>"
                "<li>Disassemble and inspect executable files <b>(DisExeFiles)</b> for in-depth analysis. </li>"
                "<li>Decompile Python <b>.pyc</b> files for reverse engineering or debugging purposes.</li>"
                "<li>Analyze Android APK files for deeper insights into mobile applications.</li>"
                "</ul>")

othertools_title = "About Other Tools Section"
othertools_text = ("The <b>Other Tools</b> section,provides an extensive set of utilities that complement cryptographic, "
                "encoding, and text-processing operations. This collection addresses a variety of needs, from key "
                "generation and randomness testing to data analysis and transformation."
                "<p><strong>Cryptographic Key Management:</strong></p>"
                "<ul>"
                "<li><b>RSA Key Generator: </b>Generate RSA key pairs for secure communications. </li>"
                "<li><b>EC Key Pair Generate: </b>Create Elliptic Curve (EC) cryptographic key pairs.</li>"
                "<li><b>DSA Key Pair Generate: </b>Generate DSA key pairs for digital signatures. </li>"
                "<li><b>PGP Key Pair Generate: </b>Create PGP (Pretty Good Privacy) key pairs for encrypted email and file sharing.</li>"
                "</ul>"
                "<p><strong>Randomness and Key Derivation:</strong></p>"
                "<ul>"
                "<li><b>Pseudo-Random Number Generator: </b>Generate pseudo-random numbers for cryptographic and other uses.</li>"
                "<li><b>PBKDF2 / Argon2 KDF: </b>Use popular key derivation functions to generate cryptographic keys from passwords.</li>"
                "</ul>"
                "<p><strong>Mathematical and Data Tools:</strong></p>"
                "<ul>"
                "<li><b>Prime Number Generator: </b>Generate prime numbers for cryptographic applications. </li>"
                "<li><b>Circular Bit Shift: </b>Perform bitwise circular shifts on binary data. </li>"
                "<li><b>Entropy: </b>Measure the randomness of input data. </li>"
                "</ul>"
                "<p><strong>Text Utilities:</strong></p>"
                "<ul>"
                "<li><b>Reverse Text: </b>Reverse input text for basic text manipulation.</li>"
                "<li><b>Frequency Analysis: </b>Analyze the frequency of characters in a given text.</li>"
                "</ul>"
                "</ul>"
                "<p><strong>Specialized tools:</strong></p>"
                "<ul>"
                "<li><b>Show on map / Show on map 2: </b>Tools to visualize geographical data on a map.</li>"
                "</ul>")

cryptanalysis_title = "About Cryptanalysis section"
cryptanalysis_text = (
    "The <b>Cryptanalysis</b> section introduces users to a variety of techniques used to evaluate and potentially compromise cryptographic systems.<br>"
    "It is designed as an educational resource to help learners understand how different attack strategies function and what cryptographic weaknesses they target. "
    "Each method is briefly explained, giving insight into its principles, prerequisites, and implications for security."
    
    "<p><strong>Classical Attacks:</strong></p>"
    "<ul>"
    "<li><strong>Known-Plaintext & Chosen-Plaintext Attacks:</strong> Analyze encrypted data with knowledge of or control over the plaintext.</li>"
    "<li><strong>Ciphertext-Only Attack:</strong> Attempt decryption using only the intercepted ciphertext.</li>"
    "<li><strong>Adaptive Chosen-Plaintext Attack:</strong> Iteratively choose plaintexts based on previous encryption results.</li>"
    "<li><strong>Brute Force & Birthday Attacks:</strong> Exhaustive key search or exploit hash collisions.</li>"
    "</ul>"
    
    "<p><strong>Advanced Cryptanalysis Techniques:</strong></p>"
    "<ul>"
    "<li><b>Differential & Linear Cryptanalysis:</b> Use statistical methods to recover encryption keys from patterns in ciphertext.</li>"
    "<li><b>Side-Channel & Power Analysis Attacks:</b> Exploit physical leakages like timing, power consumption, or electromagnetic emissions.</li>"
    "<li><b>MITM & Replay Attacks:</b> Interfere with communication to impersonate or resend messages.</li>"
    "</ul>"
    
    "<p><strong>Specialized & Emerging Threats:</strong></p>"
    "<ul>"
    "<li><b>Davies’ and XSL Attacks:</b> Apply algebraic or analytical approaches to attack block ciphers.</li>"
    "<li><b>Rubber-Hose & Black-Bag Cryptanalysis:</b> Focus on coercion or physical access to circumvent cryptographic protections.</li>"
    "<li><b>Harvest Now, Decrypt Later:</b> Store encrypted data today for decryption with future computational advances (e.g., quantum computing).</li>"
    "</ul>")
